nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

updateConfig:
  ignoreDependencies:
    - tailwindcss

patchedDependencies:
  metro: patches/metro.patch

ignorePatchFailures: true
